package com.fego.transaction.mapper;

import com.fego.transaction.common.base.BaseMapper;
import com.fego.transaction.dto.TransactionDto;
import com.fego.transaction.entity.Transaction;
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;

/**
 * @author Arun Balaji Rajasekaran
 */

@Component
public class TransactionMapper implements BaseMapper<Transaction, TransactionDto> {

    public TransactionDto domainToDto(Transaction transaction) {
        TransactionDto transactionDto = new TransactionDto();
        transactionDto.setUserId(transaction.getUserId());
        transactionDto.setAccountId(transaction.getAccountId());
        transactionDto.setStartDate(transaction.getStartDate());
        transactionDto.setEndDate(transaction.getEndDate());
        transactionDto.setAmount(transaction.getAmount());
        transactionDto.setCurrentBalance(transaction.getCurrentBalance());
        transactionDto.setBalance(transaction.getBalance());
        transactionDto.setMode(transaction.getMode());
        transactionDto.setNarration(transaction.getNarration());
        transactionDto.setReference(transaction.getReference());
        transactionDto.setTransactionTimestamp(transaction.getTransactionTimestamp());
        transactionDto.setTransactionId(transaction.getTransactionId());
        transactionDto.setValueDate(transaction.getValueDate().toString());
        transactionDto.setTransactionDateTime(transaction.getTransactionDateTime());
        transactionDto.setAmc(transaction.getAmc());
        transactionDto.setRegistrar(transaction.getRegistrar());
        transactionDto.setSchemeCode(transaction.getSchemeCode());
        transactionDto.setSchemePlan(transaction.getSchemePlan());
        transactionDto.setSchemeTypes(transaction.getSchemeTypes());
        transactionDto.setSchemeCategory(transaction.getSchemeCategory());
        transactionDto.setIsin(transaction.getIsin());
        transactionDto.setAmfiCode(transaction.getAmfiCode());
        transactionDto.setSchemeOption(transaction.getSchemeOption());
        transactionDto.setFundType(transaction.getFundType());
        transactionDto.setUcc(transaction.getUcc());
        transactionDto.setClosingUnits(transaction.getClosingUnits());
        transactionDto.setLienUnits(transaction.getLienUnits());
        transactionDto.setNav(transaction.getNav());
        transactionDto.setNavDate(transaction.getNavDate());
        transactionDto.setOrderDate(transaction.getOrderDate());
        transactionDto.setExecutionDate(transaction.getExecutionDate());
        transactionDto.setLockinDays(transaction.getLockInDays());
        transactionDto.setLockinFlag(transaction.getLockInFlag());
        transactionDto.setCost(transaction.getCost());
        transactionDto.setPremium(transaction.getPremium());
        transactionDto.setPremiumAllocationCharge(transaction.getPremiumAllocationCharge());
        transactionDto.setOtherCharges(transaction.getOtherCharges());
        transactionDto.setUnits(transaction.getUnits());
        transactionDto.setFundName(transaction.getFundName());
        transactionDto.setTransactionDate(transaction.getTransactionDate());
        transactionDto.setEmployeeDepositAmount(transaction.getEmployeeDepositAmount());
        transactionDto.setEmployerDepositAmount(transaction.getEmployerDepositAmount());
        transactionDto.setEmployeeWithdrawalAmount(transaction.getEmployeeWithdrawalAmount());
        transactionDto.setEmployerWithdrawalAmount(transaction.getEmployerWithdrawalAmount());
        transactionDto.setPensionFundAmount(transaction.getPensionFundAmount());
        transactionDto.setStatementDate(transaction.getStatementDate());
        transactionDto.setMcc(transaction.getMcc());
        transactionDto.setMaskedCardNumber(transaction.getMaskedCardNumber());
        transactionDto.setIssuerName(transaction.getIssuerName());
        transactionDto.setSymbol(transaction.getSymbol());
        transactionDto.setExchange(transaction.getExchange());
        transactionDto.setTransactionDescription(transaction.getTransactionDescription());
        transactionDto.setPrice(transaction.getPrice());
        transactionDto.setUnitsType(transaction.getUnitsType());
        transactionDto.setNumUnitsTransacted(transaction.getNumUnitsTransacted());
        transactionDto.setTradeValue(transaction.getTradeValue());
        transactionDto.setTotalCharge(transaction.getTotalCharge());
        transactionDto.setNameOfAsset(transaction.getNameOfAsset());
        transactionDto.setInvestmentDateTime(transaction.getInvestmentDateTime());
        transactionDto.setInvestmentValue(transaction.getInvestmentValue());
        transactionDto.setRedemptionDate(transaction.getRedemptionDate());
        transactionDto.setRedemptionValue(transaction.getRedemptionValue());
        transactionDto.setFundFeesPaymentDate(transaction.getFundFeesPaymentDate());
        transactionDto.setFundFeesPaymentAmount(transaction.getFundFeesPaymentAmount());
        transactionDto.setReInvestmentDate(transaction.getReInvestmentDate());
        transactionDto.setReInvestmentValue(transaction.getReInvestmentValue());
        transactionDto.setPaymentInvestorDate(transaction.getPaymentInvestorDate());
        transactionDto.setPaymentInvestorAmount(transaction.getPaymentInvestorAmount());
        transactionDto.setTaxPaidDate(transaction.getTaxPaidDate());
        transactionDto.setTaxPaidValue(transaction.getTaxPaidValue());
        transactionDto.setDividendType(transaction.getDividendType());
        transactionDto.setOrderId(transaction.getOrderId());
        transactionDto.setTradeId(transaction.getTradeId());
        transactionDto.setCompanyName(transaction.getCompanyName());
        transactionDto.setRate(transaction.getRate());
        transactionDto.setSchemeName(transaction.getSchemeName());
        transactionDto.setDpId(transaction.getDpId());
        transactionDto.setSchemeMinLotSize(transaction.getSchemeMinLotSize());
        transactionDto.setFaceValueofUnits(transaction.getFaceValueofUnits());
        transactionDto.setBrokerCode(transaction.getBrokerCode());
        transactionDto.setCurrency(transaction.getCurrency());
        transactionDto.setOtherTaxes(transaction.getOtherTaxes());
        transactionDto.setEquityCategory(transaction.getEquityCategory());
        transactionDto.setInstrumentType(transaction.getInstrumentType());
        transactionDto.setOptionType(transaction.getOptionType());
        transactionDto.setStrikePrice(transaction.getStrikePrice());
        transactionDto.setShareHolderEquityType(transaction.getShareHolderEquityType());
        transactionDto.setStt(transaction.getStt());
        transactionDto.setScheme(transaction.getScheme());
        transactionDto.setFolioNo(transaction.getFolioNo());
        transactionDto.setFirstLevelCategory(transaction.getFirstLevelCategory());
        transactionDto.setSecondLevelCategory(transaction.getSecondLevelCategory());
        transactionDto.setThirdLevelCategory(transaction.getThirdLevelCategory());
        transactionDto.setFourthLevelCategory(transaction.getFourthLevelCategory());
        transactionDto.setRemark(transaction.getRemark());
        transactionDto.setTransactionNumber(transaction.getTransactionNumber());
        transactionDto.setTier1SchemeTransactionDto(transaction.getTier1SchemeTransactionDto());
        transactionDto.setTier2SchemeTransactionDto(transaction.getTier2SchemeTransactionDto());
        transactionDto.setTier1InvestmentTransactionDto(transaction.getTier1InvestmentTransactionDto());
        transactionDto.setTier2InvestmentTransactionDto(transaction.getTier2InvestmentTransactionDto());
        transactionDto.setFegoCategory(transaction.getFegoCategory());
        transactionDto.setFegoSubCategory(transaction.getFegoSubCategory());
        transactionDto.setMerchant(transaction.getMerchant());
        transactionDto.setFegoTransactionType(transaction.getFegoTransactionType());
        transactionDto.setFixedTransaction(transaction.getFixedTransaction());
        transactionDto.setPartOfBudget(transaction.getPartOfBudget());
        transactionDto.setPartOfReport(transaction.getPartOfReport());
        transactionDto.setLocation(transaction.getLocation());
        transactionDto.setAccountType(transaction.getAccountType());
        transactionDto.setBankName(transaction.getBankName());
        transactionDto.setMaskedAccountNumber(transaction.getMaskedAccountNumber());
        transactionDto.setIsUserUpdated(transaction.getIsUserUpdated());
        transactionDto.setId(transaction.getId());
        transactionDto.setIsDeleted(transaction.isDeleted());
        transactionDto.setUpdatedAt(transaction.getUpdatedAt());
        transactionDto.setUpdatedBy(transaction.getUpdatedBy());
        transactionDto.setCreatedAt(transaction.getCreatedAt());
        transactionDto.setCreatedBy(transaction.getCreatedBy());
        return transactionDto;
    }

    public Transaction dtoToDomain(TransactionDto transactionDto) {
        Transaction transaction = new Transaction();
        transaction.setUserId(transactionDto.getUserId());
        transaction.setAccountId(transactionDto.getAccountId());
        transaction.setStartDate(transactionDto.getStartDate());
        transaction.setEndDate(transactionDto.getEndDate());
        transaction.setAmount(transactionDto.getAmount());
        transaction.setCurrentBalance(transactionDto.getCurrentBalance());
        transaction.setBalance(transactionDto.getBalance());
        transaction.setMode(transactionDto.getMode());
        transaction.setNarration(transactionDto.getNarration());
        transaction.setReference(transactionDto.getReference());
        transaction.setTransactionTimestamp(transactionDto.getTransactionTimestamp());
        transaction.setTransactionId(transactionDto.getTransactionId());
        if (StringUtils.isNotBlank(transactionDto.getValueDate()) && StringUtils.isNotEmpty(transactionDto.getValueDate())) {
            if (transactionDto.getValueDate().length() > 10) {
                Instant instant = Instant.parse(transactionDto.getValueDate());
                transaction.setValueDate(instant.atZone(ZoneId.systemDefault()).toLocalDate());
            } else {
                transaction.setValueDate(LocalDate.parse(transactionDto.getValueDate()));
            }
        }
        transaction.setTransactionDateTime(transactionDto.getTransactionDateTime());
        transaction.setAmc(transactionDto.getAmc());
        transaction.setRegistrar(transactionDto.getRegistrar());
        transaction.setSchemeCode(transactionDto.getSchemeCode());
        transaction.setSchemePlan(transactionDto.getSchemePlan());
        transaction.setSchemeTypes(transactionDto.getSchemeTypes());
        transaction.setSchemeCategory(transactionDto.getSchemeCategory());
        transaction.setIsin(transactionDto.getIsin());
        transaction.setAmfiCode(transactionDto.getAmfiCode());
        transaction.setSchemeOption(transactionDto.getSchemeOption());
        transaction.setFundType(transactionDto.getFundType());
        transaction.setUcc(transactionDto.getUcc());
        transaction.setClosingUnits(transactionDto.getClosingUnits());
        transaction.setLienUnits(transactionDto.getLienUnits());
        transaction.setNav(transactionDto.getNav());
        transaction.setNavDate(transactionDto.getNavDate());
        transaction.setOrderDate(transactionDto.getOrderDate());
        transaction.setExecutionDate(transactionDto.getExecutionDate());
        transaction.setLockInDays(transactionDto.getLockinDays());
        transaction.setLockInFlag(transactionDto.getLockinFlag());
        transaction.setCost(transactionDto.getCost());
        transaction.setPremium(transactionDto.getPremium());
        transaction.setPremiumAllocationCharge(transactionDto.getPremiumAllocationCharge());
        transaction.setOtherCharges(transactionDto.getOtherCharges());
        transaction.setUnits(transactionDto.getUnits());
        transaction.setFundName(transactionDto.getFundName());
        transaction.setEmployeeDepositAmount(transactionDto.getEmployeeDepositAmount());
        transaction.setEmployerDepositAmount(transactionDto.getEmployerDepositAmount());
        transaction.setEmployeeWithdrawalAmount(transactionDto.getEmployeeWithdrawalAmount());
        transaction.setEmployerWithdrawalAmount(transactionDto.getEmployerWithdrawalAmount());
        transaction.setPensionFundAmount(transactionDto.getPensionFundAmount());
        transaction.setStatementDate(transactionDto.getStatementDate());
        transaction.setMcc(transactionDto.getMcc());
        transaction.setMaskedCardNumber(transactionDto.getMaskedCardNumber());
        transaction.setIssuerName(transactionDto.getIssuerName());
        transaction.setSymbol(transactionDto.getSymbol());
        transaction.setExchange(transactionDto.getExchange());
        transaction.setTransactionDescription(transactionDto.getTransactionDescription());
        transaction.setPrice(transactionDto.getPrice());
        transaction.setUnitsType(transactionDto.getUnitsType());
        transaction.setNumUnitsTransacted(transactionDto.getNumUnitsTransacted());
        transaction.setTradeValue(transactionDto.getTradeValue());
        transaction.setTotalCharge(transactionDto.getTotalCharge());
        transaction.setNameOfAsset(transactionDto.getNameOfAsset());
        transaction.setInvestmentDateTime(transactionDto.getInvestmentDateTime());
        transaction.setInvestmentValue(transactionDto.getInvestmentValue());
        transaction.setRedemptionDate(transactionDto.getRedemptionDate());
        transaction.setRedemptionValue(transactionDto.getRedemptionValue());
        transaction.setFundFeesPaymentDate(transactionDto.getFundFeesPaymentDate());
        transaction.setFundFeesPaymentAmount(transactionDto.getFundFeesPaymentAmount());
        transaction.setReInvestmentDate(transactionDto.getReInvestmentDate());
        transaction.setReInvestmentValue(transactionDto.getReInvestmentValue());
        transaction.setPaymentInvestorDate(transactionDto.getPaymentInvestorDate());
        transaction.setPaymentInvestorAmount(transactionDto.getPaymentInvestorAmount());
        transaction.setTaxPaidDate(transactionDto.getTaxPaidDate());
        transaction.setTaxPaidValue(transactionDto.getTaxPaidValue());
        transaction.setDividendType(transactionDto.getDividendType());
        transaction.setOrderId(transactionDto.getOrderId());
        transaction.setTradeId(transactionDto.getTradeId());
        transaction.setCompanyName(transactionDto.getCompanyName());
        transaction.setRate(transactionDto.getRate());
        transaction.setSchemeName(transactionDto.getSchemeName());
        transaction.setDpId(transactionDto.getDpId());
        transaction.setSchemeMinLotSize(transactionDto.getSchemeMinLotSize());
        transaction.setFaceValueofUnits(transactionDto.getFaceValueofUnits());
        transaction.setBrokerCode(transactionDto.getBrokerCode());
        transaction.setCurrency(transactionDto.getCurrency());
        transaction.setOtherTaxes(transactionDto.getOtherTaxes());
        transaction.setEquityCategory(transactionDto.getEquityCategory());
        transaction.setInstrumentType(transactionDto.getInstrumentType());
        transaction.setOptionType(transactionDto.getOptionType());
        transaction.setStrikePrice(transactionDto.getStrikePrice());
        transaction.setShareHolderEquityType(transactionDto.getShareHolderEquityType());
        transaction.setStt(transactionDto.getStt());
        transaction.setScheme(transactionDto.getScheme());
        transaction.setFolioNo(transactionDto.getFolioNo());
        transaction.setFirstLevelCategory(transactionDto.getFirstLevelCategory());
        transaction.setSecondLevelCategory(transactionDto.getSecondLevelCategory());
        transaction.setThirdLevelCategory(transactionDto.getThirdLevelCategory());
        transaction.setFourthLevelCategory(transactionDto.getFourthLevelCategory());
        transaction.setRemark(transactionDto.getRemark());
        transaction.setTransactionNumber(transactionDto.getTransactionNumber());
        transaction.setTier1SchemeTransactionDto(transactionDto.getTier1SchemeTransactionDto());
        transaction.setTier2SchemeTransactionDto(transactionDto.getTier2SchemeTransactionDto());
        transaction.setTier1InvestmentTransactionDto(transactionDto.getTier1InvestmentTransactionDto());
        transaction.setTier2InvestmentTransactionDto(transactionDto.getTier2InvestmentTransactionDto());
        transaction.setFegoCategory(transactionDto.getFegoCategory());
        transaction.setFegoSubCategory(transactionDto.getFegoSubCategory());
        transaction.setMerchant(transactionDto.getMerchant());
        transaction.setFegoTransactionType(transactionDto.getFegoTransactionType());
        transaction.setFixedTransaction(transactionDto.getFixedTransaction());
        transaction.setPartOfBudget(transactionDto.getPartOfBudget());
        transaction.setPartOfReport(transactionDto.getPartOfReport());
        transaction.setLocation(transactionDto.getLocation());
        transaction.setAccountType(transactionDto.getAccountType());
        transaction.setBankName(transactionDto.getBankName());
        transaction.setMaskedAccountNumber(transactionDto.getMaskedAccountNumber());
        transaction.setIsUserUpdated(transactionDto.getIsUserUpdated());
        transaction.setCreatedBy(transactionDto.getCreatedBy());
        transaction.setUpdatedBy(transactionDto.getUpdatedBy());
        transaction.setDeleted(transactionDto.getIsDeleted());
        return transaction;
    }
}