CREATE TABLE public.transaction (
  id bigserial PRIMARY KEY,
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  amount decimal(22, 5),
  current_balance decimal(22, 5),
  balance decimal(22, 5),
  mode character varying(255),
  narration character varying(255),
  reference character varying(255),
  transaction_timestamp character varying(255),
  transaction_id character varying(255),
  type character varying(255),
  value_date date,
  transaction_date_time character varying(255),
  amc character varying(255),
  registrar character varying(255),
  scheme_code character varying(255),
  scheme_plan character varying(255),
  scheme_types character varying(255),
  scheme_category character varying(255),
  isin character varying(255),
  amfi_code character varying(255),
  scheme_option character varying(255),
  fund_type character varying(255),
  ucc character varying(255),
  closing_units decimal(22, 5),
  lien_units decimal(22, 5),
  nav character varying(255),
  nav_date date,
  order_date date,
  execution_date date,
  lock_in_days character varying(255),
  lock_in_flag character varying(255),
  cost decimal(22, 5),
  premium character varying(255),
  premium_allocation_charge decimal(22, 5),
  other_charges decimal(22, 5),
  units character varying(255),
  fund_name character varying(255),
  transaction_date date,
  employee_deposit_amount decimal(22, 5),
  employer_deposit_amount decimal(22, 5),
  employee_withdrawal_amount decimal(22, 5),
  employer_withdrawal_amount decimal(22, 5),
  pension_fund_amount decimal(22, 5),
  transaction_type character varying(255),
  statement_date date,
  mcc character varying(255),
  masked_card_number character varying(255),
  issuer_name character varying(255),
  symbol character varying(255),
  exchange character varying(255),
  transaction_description character varying(255),
  price decimal(22, 5),
  units_type character varying(255),
  num_units_transacted character varying(255),
  trade_value character varying(255),
  total_charge decimal(22, 5),
  name_of_asset character varying(255),
  investment_date_time character varying(255),
  investment_value decimal(22, 5),
  redemption_date date,
  redemption_value decimal(22, 5),
  fund_fees_payment_date date,
  fund_fees_payment_amount decimal(22, 5),
  re_investment_date date,
  re_investment_value decimal(22, 5),
  payment_investor_date date,
  payment_investor_amount decimal(22, 5),
  tax_paid_value decimal(22, 5),
  tax_paid_date date,
  dividend_type character varying(255),
  order_id character varying(255),
  trade_id character varying(255),
  company_name character varying(255),
  rate character varying(255),
  share_holer_equity_type character varying(255),
  scheme_name character varying(255),
  dp_id character varying(255),
  scheme_min_lot_size character varying(255),
  face_valueof_units character varying(255),
  broker_code character varying(255),
  currency character varying(255),
  other_taxes character varying(255),
  equity_category character varying(255),
  instrument_type character varying(255),
  option_type character varying(255),
  strike_price decimal(22, 5),
  share_holder_equity_type character varying(255),
  stt character varying(255),
  scheme character varying(255),
  folio_no character varying(255),
  first_level_category character varying(255),
  second_level_category character varying(255),
  third_level_category character varying(255),
  fourth_level_category character varying(255),
  transaction_number character varying(255),
  remark character varying(255),
  tier_one_scheme_transaction_id character varying(255),
  tier_one_scheme_transaction_date date,
  tier_one_scheme_type character varying(255),
  tier_one_scheme_id character varying(255),
  tier_one_scheme_name character varying(255),
  tier_one_scheme_narration character varying(255),
  tier_one_scheme_allocation_percent character varying(255),
  tier_one_scheme_amount decimal(22, 5),
  tier_one_scheme_nav character varying(255),
  tier_one_scheme_units character varying(255),
  tier_one_scheme_cumulative_units character varying(255),
  tier_two_scheme_transaction_id character varying(255),
  tier_two_scheme_transaction_date date,
  tier_two_scheme_type character varying(255),
  tier_two_scheme_id character varying(255),
  tier_two_scheme_name character varying(255),
  tier_two_scheme_narration character varying(255),
  tier_two_scheme_allocation_percent character varying(255),
  tier_two_scheme_amount decimal(22, 5),
  tier_two_scheme_nav character varying(255),
  tier_two_scheme_units character varying(255),
  tier_two_scheme_cumulative_units character varying(255),
  tier_one_investment_transaction_id character varying(255),
  tier_one_investment_transaction_date date,
  tier_one_investment_type character varying(255),
  tier_one_investment_narration character varying(255),
  tier_one_investment_subscriber_contribution decimal(22, 5),
  tier_one_investment_employer_contribution decimal(22, 5),
  tier_one_investment_total_contribution decimal(22, 5),
  tier_two_investment_transaction_id character varying(255),
  tier_two_investment_transaction_date date,
  tier_two_investment_type character varying(255),
  tier_two_investment_narration character varying(255),
  tier_two_investment_subscriber_contribution decimal(22, 5),
  tier_two_investment_employer_contribution decimal(22, 5),
  tier_two_investment_total_contribution decimal(22, 5),
  fego_category character varying(255),
  fego_sub_category character varying(255),
  merchant character varying(255),
  fego_transaction_type character varying(255),
  is_fixed_transaction boolean,
  is_part_of_budget boolean,
  is_part_of_report boolean,
  account_type character varying(255),
  location character varying(255),
  bank_name character varying(255),
  masked_account_number character varying(255),
  is_user_updated boolean,
  is_deleted boolean,
  created_at timestamp,
  updated_at timestamp,
  created_by bigint,
  updated_by bigint
);
CREATE TABLE public.account (
  id bigserial PRIMARY KEY,
  user_id bigint NOT NULL,
  account_type character varying(255),
  product_number character varying(255),
  masked_product_number character varying(255),
  partner_id character varying(255),
  partner_name character varying(255),
  partner_type character varying(255),
  full_name character varying(255),
  consent_id bigint,
  product_type character varying(255),
  type character varying(255),
  nominee character varying(255),
  bank_name character varying(255),
  opening_date date,
  current_od_limit decimal(22, 5),
  current_balance decimal(22, 5),
  available_credit_limit decimal(22, 5),
  credit_limit decimal(22, 5),
  drawing_limit decimal(22, 5),
  status character varying(255),
  ifsc_code character varying(255),
  branch character varying(255),
  micr_code character varying(255),
  currency character varying(255),
  facility character varying(255),
  longitude character varying(255),
  latitude character varying(255),
  fip_id character varying(255),
  link_account_reference_number character varying(255),
  is_account_linked boolean,
  due_date date,
  current_due decimal(22, 5),
  image character varying(255),
  is_deleted boolean,
  created_at timestamp,
  updated_at timestamp,
  created_by bigint,
  updated_by bigint
);

CREATE TABLE public.goal (
  id bigserial PRIMARY KEY,
  user_id bigint NOT NULL,
  name character varying(255),
  target_date date,
  target_amount decimal(22, 5),
  goal_category integer,
  image character varying(255),
  is_completed boolean,
  last_pop_up_date date,
  is_deleted boolean,
  created_at timestamp,
  updated_at timestamp,
  created_by bigint,
  updated_by bigint
);

CREATE TABLE public.rule (
  id bigserial PRIMARY KEY,
  goal_id bigint,
  rule_id integer,
  auto_deduct_amount decimal(22, 5),
  is_deleted boolean,
  created_at timestamp,
  updated_at timestamp,
  created_by bigint,
  updated_by bigint
);

CREATE TABLE public.peer_user (
  id bigserial PRIMARY KEY,
  user_id bigint NOT NULL,
  age integer NULL,
  gender character varying(30) NULL,
  tier character varying(30) NULL,
  average_monthly_income decimal(22, 5) NULL,
  no_of_transactions_per_month integer NULL,
  peer_group_id bigint,
  average_peer_goal_saving_amount decimal(22, 5) NULL,
  fego_score_percentile integer NULL,
  auto_deduct_frequency integer NULL,
  instant_save_frequency integer NULL,
  round_up_frequency integer NULL,
  categories character varying(500) NULL,
  account_average_balance decimal(22, 5),
  average_fixed_salary_income decimal(22, 5),
  average_fixed_non_salary_income decimal(22, 5),
  average_varying_income decimal(22, 5),
  average_fixed_expenses decimal(22, 5),
  average_variable_expenses decimal(22, 5),
  primary_account_id bigint,
  goal_save_amount decimal(22, 5),
  free_cash_amount decimal(22, 5),
  is_deleted boolean,
  created_at timestamp,
  updated_at timestamp,
  created_by bigint,
  updated_by bigint
);

CREATE TABLE public.savings_meta (
  id bigserial PRIMARY KEY,
  full_size_image character varying(255),
  name character varying(255),
  category character varying(255),
  thumbnail_image character varying(255),
  is_deleted boolean,
  created_at timestamp,
  updated_at timestamp,
  created_by bigint,
  updated_by bigint
);

INSERT INTO public.savings_meta
  VALUES (1, 'image1', 'Paris', 'GoSomewhere', 'Paris-Thumbnail', 'FALSE', '2020-12-31 9:24:04', '2020-12-31 13:34:05', 0, 0),
  (2, 'image2', 'Australia', 'GoSomewhere', 'Australia-Thumbnail', 'FALSE', '2020-12-31 9:24:04', '2020-12-31 13:34:05', 0, 0),
  (3, 'image3', 'London', 'GoSomewhere', 'London-Thumbnail', 'FALSE', '2020-12-31 9:24:04', '2020-12-31 13:34:05', 0, 0),
  (4, 'image4', 'Himalayas', 'GoSomewhere', 'Himalayas-Thumbnail', 'FALSE', '2020-12-31 9:24:04', '2020-12-31 13:34:05', 0, 0),
  (5, 'image5', 'Taj Mahal', 'GoSomewhere', 'Taj Mahal-Thumbnail', 'FALSE', '2020-12-31 9:24:04', '2020-12-31 13:34:05', 0, 0),
  (6, 'image6', '', 'GetSomewhereCreateOwn', 'Create Own (Place)-Thumbnail', 'FALSE', '2020-12-31 9:24:04', '2020-12-31 13:34:05', 0, 0),
  (7, 'image7', 'Home', 'GetSomething', 'Home-Thumbnail', 'FALSE', '2020-12-31 9:24:04', '2020-12-31 13:34:05', 0, 0),
  (8, 'image8', 'Phone', 'GetSomething', 'Phone-Thumbnail', 'FALSE', '2020-12-31 9:24:04', '2020-12-31 13:34:05', 0, 0),
  (9, 'image9', 'Laptop', 'GetSomething', 'Laptop-Thumbnail', 'FALSE', '2020-12-31 9:24:04', '2020-12-31 13:34:05', 0, 0),
  (10, 'image10', 'Bike', 'GetSomething', 'Bike-Thumbnail', 'FALSE', '2020-12-31 9:24:04', '2020-12-31 13:34:05', 0, 0),
  (11, 'image11', 'PS5', 'GetSomething', 'PS5-Thumbnail', 'FALSE', '2020-12-31 9:24:04', '2020-12-31 13:34:05', 0, 0),
  (12, 'image12', '', 'GetSomethingCreateOwn', 'Create Own (Asset)-Thumbnail', 'FALSE', '2020-12-31 9:24:04', '2020-12-31 13:34:05', 0, 0);

CREATE TABLE public.consent (
  id bigserial PRIMARY KEY,
  consent_expiry character varying(255),
  consent_id character varying(255),
  consent_start character varying(255),
  customer_vua character varying(255),
  fi_data_from character varying(255),
  fi_data_to character varying(255),
  frequency_unit character varying(255),
  frequency_value integer,
  user_id bigint NOT NULL,
  is_deleted boolean,
  created_at timestamp,
  updated_at timestamp,
  created_by bigint,
  updated_by bigint
);

CREATE TABLE public.saving (
  id bigserial PRIMARY KEY,
  goal_id bigint NOT NULL,
  user_id bigint NOT NULL,
  rule_name character varying(255),
  transaction_date date,
  amount decimal(22, 5),
  transaction_id bigint,
  account_id bigint,
  merchant character varying(255),
  bank_name character varying(255),
  masked_product_number character varying(255),
  is_deleted boolean,
  created_at timestamp,
  updated_at timestamp,
  created_by bigint,
  updated_by bigint
);

CREATE TABLE public.category (
  id bigserial PRIMARY KEY,
  partner_name character varying(255),
  fego_category character varying(255),
  fego_sub_category character varying(255),
  first_level_category character varying(255),
  second_level_category character varying(255),
  third_level_category character varying(255),
  fego_transaction_type character varying(255),
  is_fixed_transaction boolean,
  is_part_of_budget boolean,
  is_part_of_report boolean,
  is_deleted boolean,
  created_at timestamp,
  updated_at timestamp,
  created_by bigint,
  updated_by bigint
);

CREATE TABLE public.financial_calendar (
  id bigserial PRIMARY KEY,
  user_id bigint,
  start_date_range date,
  end_date_range date,
  transaction_type character varying(255),
  fego_category character varying(255),
  fego_sub_category character varying(255),
  proposed_transaction_date date,
  actual_transaction_date date,
  amount decimal(22, 5),
  transaction_flag character varying(255),
  is_deleted boolean,
  created_at timestamp,
  updated_at timestamp,
  created_by bigint,
  updated_by bigint
);